# Generated by Django 2.2.17 on 2021-04-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='количество'),
        ),
    ]
