# Generated by Django 2.2.17 on 2021-03-27 08:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_create_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 8, 56, 47, 343342, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
