# Generated by Django 2.2.17 on 2021-04-02 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0007_auto_20210327_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 4, 18, 39, 8, 299372, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
